### ISSUE TITLE
Problem installing dummy VNFM

### ISSUE THREAD

**Issue by tahirokian** [openbaton/dummy-vnfm-amqp#3]
I am trying to install dummy-vnfm-amqp to test my NFVO installation but getting the following error when I run ./dummy-vnfm-sh compile:

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/openbaton/dummy-vnfm-amqp/build.gradle' line: 23

* What went wrong:
Error resolving plugin [id: 'net.researchgate.release', version: '2.1.2']
> Could not GET 'https://plugins.gradle.org/api/gradle/2.4/plugin/use/net.researchgate.release/2.1.2'.
   > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Please help me with that.

**Comment by gc4rella** [comment]
There is a problem with the gradle wrapper version available in the project. I just pushed a patch on the develop branch, which will be merged with master in the next days.

In the meanwhile you could checkout the develop branch and compile that version which will fix this problem. 

Please confirm.

**Comment by tahirokian** [comment]
It worked. Thanks a lot.

**Comment by gc4rella** [comment]
we noticed that after my changes there were issues with starting the component. Could you please confirm that after a git pull all is fine on your side ?

**Comment by tahirokian** [comment]
The installation with develop branch was fine but dummy-vnfm-amqp does not start. I have tested my installation with dummy-vnfm-rest and that worked fine.

**Comment by gc4rella** [comment]
yeah...with the latest changes it should start properly. if you confirm I'll close this issue. Thx!

**Comment by tahirokian** [comment]
Its working now.

**Comment by gc4rella** [comment]
great.
